name: Deploy preview
on: pull_request

jobs:
  build-diary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec nanoc

    - uses: netlify/actions/cli@master
      id: netlify-deploy
      with:
        args: deploy --dir=output
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
