name: Production deploy
on:
  push:
    branches:
      - main

jobs:
  build-diary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec nanoc

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npx -y --verbose netlify-cli deploy --dir=output --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
