name: My workflow
on:
  push:
    branches:
      - main

jobs:
  build-diary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec nanoc
